BE/README.md
=> [BE]test: init

.gitignore, FE/.eslintignore, FE/.eslintrc, FE/.prettierrc, FE/babel.config.js, FE/config/webpack.config.common.js, FE/config/webpack.config.dev.js, FE/config/webpack.config.prod.js, FE/package-lock.json, FE/package.json, FE/src/index.html, FE/src/index.tsx, FE/tsconfig.json
- Webpack 설정
- Babel 설정
- tsconfig 설정
- eslint 설정
- prettier 설정
- 기술문서 참조
- close #3,5,6
=> [FE] 초기 설정( Webpack, Babel, tsconfig, eslint, prettier)

.gitignore, FE/next-env.d.ts, FE/package-lock.json, FE/package.json, FE/src/pages/index.tsx, FE/tsconfig.json
- next.js 설치
- webpack 버전 낮춤
- pages 디렉토리 생성 및 테스트
- webpack의 버전을 4로 낮춤. 현재 next dev 명령어가 wepback 5버전에서 수행이 안되는 버그가 존재하기 때문
- close #9
=> [FE] next.js 설치 및 pages 디렉토리 생성

BE/user/build.gradle, BE/user/src/main/java/com/everyportfolio/user/configuration/SwaggerConfiguration.java, BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java, BE/user/src/main/resources/application.properties, BE/user/src/test/java/com/everyportfolio/user/RefreshTokenTests.java, BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
Swagger 공부 및 User API에 대한 Swagger 셋팅 완료
- Swagger 셋팅
- User API에 Swagger Config 추가와 Swagger UI 추가
- User API의 Context-path를 user로 설정함
- close #16
=> [BE]feat: Swagger 구현-#16

FE/package-lock.json, FE/package.json, FE/src/api/index.ts, FE/src/components/LoginComponent/LoginComponent.tsx, FE/src/components/LoginComponent/RightComponent/RightComponent.tsx, FE/src/container/LoginContainer/RightContainer.tsx, FE/src/pages/index.tsx, FE/src/store/modules/index.ts, FE/src/store/store.ts
- Redux-Persist 적용
-  Container Component & Presentation Component 분리
- 내용을 적어주세요. (리뷰 할 때 중요한 부분을 적어두도록 합시다.)
- close #30
=> [FE] Redux-Persist 적용 및 Container Component & Presentation Component 분리

BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java
- login return 값을 name으로 수정
- profile return 값을 id, name의 json 형식으로 리턴
- login 완료시 responseentity에 name을 넣어서 return
- profile 에서 access token을 분석하고 id 가져와서 name을 찾은후 id, name의 형식의 json으로 리턴
- close #56 
- close #59
=> [BE] login return 값 수정 & profile return 값 수정

BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java, BE/user/src/main/resources/mybatis-mapper/UserMapper.xml
user delete 기능 완성
logout때 blacklist 구현할 예정
- User Delete 기능 완성
- User Delete 기능을 위해서 /user/delete를 만들고 delete method로 해두고 userService와 userMapper에 delete 코드, mybatis에 delete SQL을 만듬
- close #61
=> [BE] 유저 삭제 기능 완성

BE/user/src/main/java/com/everyportfolio/user/DTO/LoginDTO.java, BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java, BE/user/src/main/resources/mybatis-mapper/UserMapper.xml, BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
- /user/logout 기능 구현
- access token을 받아서 db에 있는 refresh token의 token 부분을 null로 만들어 login시 발급된 refresh token으로 더이상 access token을 발급되지 않도록 막음
- close #68
=> [BE] logout 기능 구현

BE/user/src/main/java/com/everyportfolio/user/DTO/PasswordChangeDTO.java, BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/mapper/RedisPasswordChangeMapper.java, BE/user/src/main/java/com/everyportfolio/user/mapper/UserMapper.java, BE/user/src/main/java/com/everyportfolio/user/model/RedisPasswordChange.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java, BE/user/src/main/resources/mybatis-mapper/UserMapper.xml, BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
- 유저 패스워드 변경을 위한 email 인증
- 유저 패스워드 변경
- /user/find-pwd : id 확인후 token 이메일로 전송 그리고 redis 저장
- /user/email-authentication-pwd : id, token을 redis의 것과 비교
- /user/change-pwd : id, token 확인후 password 변경
- close #58
=> [BE] 유저 비밀번호 변경 기능 제작

BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java, BE/user/src/main/java/com/everyportfolio/user/exception/PasswordLengthNotAllowedException.java, BE/user/src/test/java/com/everyportfolio/user/RefreshTokenTests.java, BE/user/src/test/java/com/everyportfolio/user/UserApplicationTests.java
- Exception Handler 추가
- PasswordLengthNotAllowedException 추가
- Exception Handler를 추가했음(UserController에서 나오는 Exception 류임 servlet에서 나오는 에러는 400이나 404등 알아서 처리되기에 큰 신경안씀.. 혹시 따로 처리해야된다면 추가해볼 예정)
- PasswordLengthNotAllowedException 추가함
=> [BE] Exception Handler 추가와 PasswordLengthNotAllowedException 추가

BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java
- Controller에서 return json 형식 맞추기
- Error Handler에서 return Json 형식 맞추기
- 전부 return 값을 ResponseEntity<HashMap<String, Object>>로 맞추고 status와 message 필드를 필수로 넣음
=> [BE] Json Response 형식 맞추기

BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/exception/EmailAuthenticationFailedException.java, BE/user/src/main/java/com/everyportfolio/user/exception/EmailRegularExpressionNotMatchedException.java, BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java, BE/user/src/main/java/com/everyportfolio/user/exception/IdDuplicatedException.java, BE/user/src/main/java/com/everyportfolio/user/exception/LoginDeniedException.java, BE/user/src/main/java/com/everyportfolio/user/exception/RefreshTokenDifferentException.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
- Controller 및 Service에서 나올만한 Error 상황 정리
- 그에 맞는 Exception 들 추가
- Error 상황 정리해서 Exception 을 날림
- Exception들 종류별로 만들어서 붙여넣음.
- GlobalExceptionHandler에서 Exception들 잡아서 처리함
- close #60
=> [BE] Error 상황 정리 & Exception 추가

BE/user/build.gradle, BE/user/src/main/java/com/everyportfolio/user/DTO/LoginDTO.java, BE/user/src/main/java/com/everyportfolio/user/DTO/PasswordChangeDTO.java, BE/user/src/main/java/com/everyportfolio/user/DTO/UserDTO.java, BE/user/src/main/java/com/everyportfolio/user/controller/UserController.java, BE/user/src/main/java/com/everyportfolio/user/exception/GlobalExceptionHandler.java, BE/user/src/main/java/com/everyportfolio/user/service/EmailService.java, BE/user/src/main/java/com/everyportfolio/user/service/UserService.java
- email 버그 수정
- password null 처리 수정
- requset에 null이 들어오는 오류 수정
- email 버그를 수정하기 위해서 createMessage를 send전에 항상하도록 해줘서 새로운 메세지 생성
- password null처리를 위해서 user가 null일 경우 false return
- request에 null값이 들어오면 안되는 경우 Valid Annotation을 통해서 해결
=> [BE] User API 버그 수정

BE/api_gateway/src/main/java/com/everyportfolio/api_gateway/filter/PortfolioFilter.java, BE/api_gateway/src/main/java/com/everyportfolio/api_gateway/filter/ResourceFilter.java, BE/api_gateway/src/main/resources/application.yml, BE/docker-compose.yml
- nginx docker-compose에 추가
- api gateway에서 nginx route 설정
- docker-compose에 nginx image 추가 (추후 volumes에 front-end 파일 추가)
- api gateway의 application.yml에 nginx route 추가
- ResourceFilter 추가
- PortfolioFilter의 log 수정
=> [BE] Resource Server용 Nginx를 위해 API Gateway의 Route 추가

BE/portfolio/build.gradle, BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/AccessTokenDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/PortfolioApplication.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/configuration/DatabaseConfiguration.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/application.properties, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/user/src/main/java/com/everyportfolio/user/configuration/DatabaseConfiguration.java
- portfolio create를 위한 insert문 제작
- portfolio create를 위해 Controller, Service, Mapper 제작
- create를 위해서 insert문을 mybatis-mapper에 만듦.
- create를 위해 Controller에 PostMapping 해둔 메소드 제작, Service에 CreatePortfolio 메소드 제작, Mapper에 InsertPortfolio 제작
- close #77
=> [BE] portfolio/create 제작

BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioContentDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioTitleDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- portfolio update title URL 제작
- portfolio update content URL 제작
- update 시 tableId에서 찾은 userId와 accesstoken의 userid가 같은시 검사함
- update title시 title만, update content시 content와 template_type을 update함
- close #80
=> [BE] portfolio update 기능 제작

BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioDeleteDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- portfolio delete 기능 제작
- Controller에 DeleteMapping한 Method 추가, table id에 맞는 user id와 access token의 id가 매칭되는지 확인함
- Delete SQL 추가
- close #78
=> [BE] portfolio delete 기능 제작

.github/workflows/FE.deploy.yml
=> [FE] 배포 테스트

BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/LikeListMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/model/Portfolio.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/mybatis-mapper/LikeListMapper.xml, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio View 기능을 위해서 Portfolio 내용 들고 오기
- Like_List에서 Like 갯수 가져오기
- Like_List용 Mapper, XML, Service 추가 & Count를 통해 Like 갯수 가져오기
- Portfolio Model 추가 & ResultMap을 통해 Mapping 시켜줌
- Portfolio 내용 가져와서 Controller에서 Json 바꿔서 Return
- close #82
=> [BE] Portfolio View 기능 제작

BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioLikeDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/LikeListMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/mybatis-mapper/LikeListMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio Like switch 기능 추가
- /portfolio/like post 메소드 추가
- PortfolioService에 TableId에 맞는 portfolio가 있는지 확인하는 코드 추가
=> [BE] Portfolio Like switch 기능 추가

BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/LikeListService.java, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio Like 확인해주는 Get Method URL 추가
- PortfolioController에 Like Get Method 추가
- LikeListService에 Like가 있는지 없는지 확인해주는 Method 추가
- close #106
=> [BE] Portfolio Like 확인해주는 Get Method URL 추가

.github/workflows/FE.deploy.yml, FE/src/components/SignUpComponent/RightComponent/RightComponent.tsx, FE/src/container/SignUpContainer/RightContainer.tsx, FE/src/hooks/index.ts, FE/src/hooks/useDebounce.ts, FE/src/hooks/useInput.ts
- useDebounce 구현 및 적용
- useInput 구현 및 적용
- 자동배포 yml 파일 수정
```javascript
const debounceEmail = useDebounce({ stateValue: email, delay: 2000 });
useEffect(() => {
if (debounceEmail === '') return;
console.log('debounce effect');
checkIDAPI({ id: debounceEmail })
.then(() => {
setDuplication(true);
})
.catch(() => {
setDuplication(false);
});
}, [debounceEmail]);
```
디바운스 사용방법 정리하기
- close #10, #35
=> [FE] Custom Hook 구현 및 적용 + 회원가입 수정

FE/src/components/common/DropDown.tsx, FE/src/components/common/Header.tsx, FE/src/components/common/NavLink.tsx, FE/src/container/LoginContainer/RightContainer.tsx, FE/src/pages/index.tsx, FE/src/pages/login.tsx, FE/src/store/modules/user.ts, FE/src/styles/GlobalStyle.ts
- 검색창 프레임 구현
- 로그인 기능 표시
- 드랍다운 구현
- 로그아웃 기능 구현
- 내용을 적어주세요. (리뷰 할 때 중요한 부분을 적어두도록 합시다.)
- close #38, #111, #41, #42
=> [FE] Main Page Header (검색창, 드랍다운, 로그아웃) 구현

BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/model/PortfolioWithThumbnail.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio 최신순 Search 기능 구현
- Portfolio 좋아요순 Search 기능 구현
- Portfolio 최신순 Search 기능을 위해서 SQL 만듬.Like_list 랑 Portfolio 테이블 조인을 통해서 LikeCount 계산
- Portfolio 좋아요순 Search 기능을 위해서 SQL 만듬. 위와 마찬가지 임
- close #83
=> [BE] Portfolio Search 기능 구현

BE/portfolio/src/main/java/com/everyportfolio/portfolio/DTO/PortfolioDTO.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/mapper/PortfolioMapper.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/service/PortfolioService.java, BE/portfolio/src/main/resources/application.properties, BE/portfolio/src/main/resources/mybatis-mapper/PortfolioMapper.xml, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio Create 기능에서 ThumbnailURL을 넣도록 수정
- DefaultThumbnailURL 지정
- Create시 ThumbnailURL 입력
- SQL에서 ThumbnailURL 넣도록 바꿈
=> [BE] Portfolio Create 기능 ThumbnailURL 추가하도록 수정

FE/src/components/MyPortfolio/EditButton/EditButton.tsx, FE/src/components/MyPortfolio/MyPortfolio.tsx, FE/src/pages/myportfolio.tsx
- MyPortfolio 페이지 구현
- MyPortfolio 생성/수정을 위한 버튼 구현
- 헤더 적용
- 내용을 적어주세요. (리뷰 할 때 중요한 부분을 적어두도록 합시다.)
- close #79, #81
=> [FE]MyPortfolio 페이지 생성/수정 구현

BE/portfolio/build.gradle, BE/portfolio/src/main/java/com/everyportfolio/portfolio/configuration/SwaggerConfiguration.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/EmailRegularExpressionNotMatchedException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/GlobalExceptionHandler.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotEqualToWriterException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotExistLikeCountException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotExistPortfolioException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/NotVaildTypeException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/TooLongThumbnailURLException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/TooLongTitleException.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/utility/RegularExpressionUtility.java, BE/portfolio/src/test/java/com/everyportfolio/portfolio/PortfolioApplicationTests.java
- Portfolio API Exception 처리
- Portfolio API에서 나올 수 있는 각종 Exception 상황들을 처리함. 자세한 내용은 Wiki의 에러코드목록 참조
- close #85
=> [BE] Portfolio API Exception 처리

BE/portfolio/src/main/java/com/everyportfolio/portfolio/controller/PortfolioController.java, BE/portfolio/src/main/java/com/everyportfolio/portfolio/exception/GlobalExceptionHandler.java
- exception 상황 추가 수정
- update/title 에서 exception 적용이 안된 문제 해결
- GlobalExceptionHandler에서 Forbidden을 Unauthorized로 보낸 문제 고침
- close #85
=> [BE] exception 상황 추가 수정
